"""
Automated Test Suite for Multi-Provider AI Fallback Engine
Tests:
TEST A: Groq configured + successful -> Groq called, OpenAI NOT called
TEST B: Groq returns 429 -> Groq attempted, OpenAI automatically called
TEST C: Groq timeout -> OpenAI fallback
TEST D: Groq 5xx -> OpenAI fallback
TEST E: Groq unavailable + OpenAI unavailable -> honest fallback, no fabricated answer
TEST F: Health/status -> provider configuration shown, NO secrets exposed
TEST G: PostgreSQL authority -> deterministic values unchanged
TEST H: All existing API contracts remain compatible
"""
import unittest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient

from backend.main import app
from backend.ai_provider import (
    AIService,
    GroqProvider,
    OpenAIProvider,
    ProviderUnavailableError,
    AllProvidersUnavailableError,
    AIProviderResult,
    ai_service
)
from backend.assistant import handle_assistant_query


class TestGroqOpenAIFallbackArchitecture(unittest.TestCase):
    def setUp(self):
        self.client = TestClient(app)

    def test_a_groq_success_openai_not_called(self):
        """TEST A: Groq configured + successful -> Groq called, OpenAI NOT called."""
        test_service = AIService()

        mock_groq = MagicMock()
        mock_groq.name = "groq"
        mock_groq.is_configured.return_value = True
        mock_groq.generate.return_value = AIProviderResult(
            text="Grounded narrative synthesized by Groq",
            provider="groq",
            model="groq/compound-mini"
        )

        mock_openai = MagicMock()
        mock_openai.name = "openai"
        mock_openai.is_configured.return_value = True

        test_service.providers = {"groq": mock_groq, "openai": mock_openai}

        result = test_service.generate_narrative("System prompt", "User prompt")
        self.assertEqual(result.provider, "groq")
        self.assertEqual(result.text, "Grounded narrative synthesized by Groq")
        mock_groq.generate.assert_called_once()
        # Verify OpenAI was NOT called unnecessarily (no duplicate token burn)
        mock_openai.generate.assert_not_called()

    def test_b_groq_429_openai_fallback(self):
        """TEST B: Groq returns 429 -> Groq attempted, OpenAI automatically called."""
        test_service = AIService()

        mock_groq = MagicMock()
        mock_groq.name = "groq"
        mock_groq.is_configured.return_value = True
        mock_groq.generate.side_effect = ProviderUnavailableError(
            "Groq quota or rate limit exceeded (HTTP 429)",
            status_code=429,
            provider="groq"
        )

        mock_openai = MagicMock()
        mock_openai.name = "openai"
        mock_openai.is_configured.return_value = True
        mock_openai.generate.return_value = AIProviderResult(
            text="Narrative generated by OpenAI fallback",
            provider="openai",
            model="gpt-4o-mini"
        )

        test_service.providers = {"groq": mock_groq, "openai": mock_openai}

        result = test_service.generate_narrative("System prompt", "User prompt")
        self.assertEqual(result.provider, "openai")
        self.assertEqual(result.text, "Narrative generated by OpenAI fallback")
        mock_groq.generate.assert_called_once()
        mock_openai.generate.assert_called_once()

    def test_c_groq_timeout_openai_fallback(self):
        """TEST C: Groq timeout -> OpenAI fallback."""
        test_service = AIService()

        mock_groq = MagicMock()
        mock_groq.name = "groq"
        mock_groq.is_configured.return_value = True
        mock_groq.generate.side_effect = ProviderUnavailableError(
            "Groq request timed out after 15.0s",
            status_code=408,
            provider="groq"
        )

        mock_openai = MagicMock()
        mock_openai.name = "openai"
        mock_openai.is_configured.return_value = True
        mock_openai.generate.return_value = AIProviderResult(
            text="Narrative from OpenAI following Groq timeout",
            provider="openai",
            model="gpt-4o-mini"
        )

        test_service.providers = {"groq": mock_groq, "openai": mock_openai}

        result = test_service.generate_narrative("System prompt", "User prompt")
        self.assertEqual(result.provider, "openai")
        self.assertEqual(result.text, "Narrative from OpenAI following Groq timeout")
        mock_groq.generate.assert_called_once()
        mock_openai.generate.assert_called_once()

    def test_d_groq_5xx_openai_fallback(self):
        """TEST D: Groq 5xx -> OpenAI fallback."""
        test_service = AIService()

        mock_groq = MagicMock()
        mock_groq.name = "groq"
        mock_groq.is_configured.return_value = True
        mock_groq.generate.side_effect = ProviderUnavailableError(
            "Groq upstream server error (HTTP 503)",
            status_code=503,
            provider="groq"
        )

        mock_openai = MagicMock()
        mock_openai.name = "openai"
        mock_openai.is_configured.return_value = True
        mock_openai.generate.return_value = AIProviderResult(
            text="Narrative from OpenAI following Groq 503",
            provider="openai",
            model="gpt-4o-mini"
        )

        test_service.providers = {"groq": mock_groq, "openai": mock_openai}

        result = test_service.generate_narrative("System prompt", "User prompt")
        self.assertEqual(result.provider, "openai")
        self.assertEqual(result.text, "Narrative from OpenAI following Groq 503")
        mock_groq.generate.assert_called_once()
        mock_openai.generate.assert_called_once()

    def test_e_both_unavailable_honest_fallback(self):
        """TEST E: Groq unavailable + OpenAI unavailable -> honest fallback, no fabricated answer, no crash."""
        with patch.object(ai_service, "generate_narrative") as mock_gen:
            mock_gen.side_effect = AllProvidersUnavailableError("Both providers failed")

            response = handle_assistant_query("Who is the top researcher?")
            self.assertEqual(response["provider"], "fallback_database")
            self.assertIn("AI narrative synthesis is temporarily unavailable", response["answer"])
            # Verify PostgreSQL metrics are still present, 100% accurate, and uncompromised
            self.assertIn("keyFindings", response)
            self.assertIn("evidence", response)
            self.assertIn("supportingData", response)
            self.assertTrue(len(response["keyFindings"]) > 0)
            self.assertTrue(len(response["evidence"]) > 0)

    def test_f_health_status_no_secrets_exposed(self):
        """TEST F: Health/status -> provider configuration shown, NO secrets exposed."""
        resp = self.client.get("/api/v1/health")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn("ai", data)
        ai_stat = data["ai"]
        self.assertEqual(ai_stat["primary_provider"], "groq")
        self.assertEqual(ai_stat["fallback_provider"], "openai")
        self.assertIn("groq", ai_stat["providers"])
        self.assertIn("openai", ai_stat["providers"])

        # Ensure NO key, secret, or token strings are leaked
        for k, v in ai_stat["providers"].items():
            self.assertNotIn("key", v)
            self.assertNotIn("api_key", v)
            self.assertNotIn("secret", v)
            self.assertNotIn("token", v)
            self.assertNotIn("authorization", v)

        # Dedicated /api/v1/ai/status
        status_resp = self.client.get("/api/v1/ai/status")
        self.assertEqual(status_resp.status_code, 200)
        status_data = status_resp.json()
        self.assertEqual(status_data["priority"], ["groq", "openai"])

    @patch("backend.assistant.ai_service.generate_narrative")
    def test_g_postgresql_authority_unchanged(self, mock_gen):
        """TEST G: PostgreSQL authority -> Verify deterministic values remain unchanged."""
        mock_gen.return_value = AIProviderResult(
            text="Grounded narrative for rankings",
            provider="groq",
            model="groq/compound-mini"
        )
        response = handle_assistant_query("Who is the top researcher?")
        
        # Verify the deterministic data structure
        top_researchers = response["supportingData"].get("top_researchers", [])
        self.assertTrue(len(top_researchers) > 0)
        top1 = top_researchers[0]
        self.assertEqual(top1["name"], "Dr. Ramesh Rao")
        self.assertEqual(top1["score"], 99.1)
        self.assertEqual(top1["dept"], "MECH")
        self.assertEqual(top1["rank"], 1)

    @patch("backend.assistant.ai_service.generate_narrative")
    def test_h_all_api_contracts_compatible(self, mock_gen):
        """TEST H: All existing API contracts remain compatible."""
        mock_gen.return_value = AIProviderResult(
            text="Grounded narrative for HSS",
            provider="groq",
            model="groq/compound-mini"
        )
        resp = self.client.post("/api/v1/assistant/query", json={"question": "Summarize HSS department"})
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn("answer", data)
        self.assertIn("keyFindings", data)
        self.assertIn("evidence", data)
        self.assertIn("supportingData", data)
        self.assertIn("relatedQuestions", data)
        self.assertEqual(data["provider"], "groq")


if __name__ == "__main__":
    unittest.main(verbosity=2)
